-- Run as HRMS_APP in SQL*Plus. Keeps your existing data (unlike schema.sql, which wipes it).

-- 1. Stop the ID jumps: no identity caching (was the default CACHE 20 -> your 1, 2, 21).
alter table departments modify (
   department_id generated by default as identity ( nocache )
);
alter table employees modify (
   employee_id generated by default as identity ( nocache )
);

-- 2. Next new ID = highest existing ID + 1 (closes the gap at the END of the sequence).
alter table departments modify (
   department_id generated by default as identity ( restart start with limit value )
);
alter table employees modify (
   employee_id generated by default as identity ( restart start with limit value )
);

-- 3. Block deleting a department that still has employees (was ON DELETE SET NULL).
alter table employees drop constraint fk_employee_department;
alter table employees
   add constraint fk_employee_department foreign key ( department_id )
      references departments ( department_id );

commit;