-- 1. Drop child table first (or drop with CASCADE CONSTRAINTS)
begin
   execute immediate 'DROP TABLE employees CASCADE CONSTRAINTS';
exception
   when others then
      if sqlcode != -942 then
         raise;
      end if;
end;
/

begin
   execute immediate 'DROP TABLE departments CASCADE CONSTRAINTS';
exception
   when others then
      if sqlcode != -942 then
         raise;
      end if;
end;
/

-- 2. Create Departments table
create table departments (
   department_id   number generated by default as identity ( start with 1 increment by 1 ) primary key,
   department_name varchar2(100) not null,
   location        varchar2(100),
   constraint uq_department_name unique ( department_name )
);

-- 3. Create Employees table
create table employees (
   employee_id   number generated by default as identity ( start with 1 increment by 1 ) primary key,
   first_name    varchar2(50) not null,
   last_name     varchar2(50) not null,
   email         varchar2(120) not null,
   phone         varchar2(20),
   hire_date     date default sysdate not null,
   job_title     varchar2(80),
   salary        number(10,2),
   department_id number,
   constraint uq_employee_email unique ( email ),
   constraint fk_employee_department foreign key ( department_id )
      references departments ( department_id )
         on delete set null
);

-- 4. Create Index on Foreign Key
create index ix_employees_department_id on
   employees (
      department_id
   );

-- 5. Insert Seed Data
insert into departments (
   department_name,
   location
) values
   ( 'Engineering',
     'Pune' );
insert into departments (
   department_name,
   location
) values
   ( 'Human Resources',
     'Mumbai' );
insert into departments (
   department_name,
   location
) values
   ( 'Sales',
     'Bangalore' );


select username,
       account_status,
       lock_date
  from dba_users
 where username = upper('hrms_app');